### PR TITLE
Add methods to get names

### PR DESCRIPTION
**Pull request by Shir0kamii**
Allow to use these methods outside of the class

@ramnes This time everything should be ok

### CODE REVIEW

**Comment by ramnes** [comment]
What about making those two methods classmethods?

**Comment by Shir0kamii** [comment]
Just so that you're not surprised with the code, I was forced to apply the `classmethod` decorator afterward as it can't be stacked with the `classproperty` decorator.

**Comment by ramnes** [comment]
Can't we get the `classproperty` decorator works with classmethods? :grin:

**Comment by ramnes** [comment]
I've gone ahead and implemented it in fa84df6. :wink:

**Pull request closed without merging**
